### ISSUE TITLE
Requirements for non-condas users?

### ISSUE THREAD

**Issue by DirtBurner** [mrsiegfried/Venturelli2020-GRL#1]
Would it be possible to include a `requirements.txt` file in this repo for users who don't use condas? `environments.yml` is condas-specific. A requirements file can be generated with `pip freeze > requirements.txt` or `conda list -e > requirements.txt`. In case that doesn't work, can you verify which version of condas and python you used to generate the maps?

**Comment by mrsiegfried** [comment]
Hi Brad,

You can trivially make a requirements.txt but opening the environment.yml file and copying the dependencies into a requirements.txt file (though be sure to get the formatting right by removing the leading `-` and adding a second `=`). I should point out that [PyGMT recommends](https://www.pygmt.org/dev/install.html#installing-pygmt) installing using `conda`, so I have not tested this notebook with PyPi. Any version of Anaconda should work, but you did make me realize I had never finished up my `environment.yml` file by freezing the versions (and removing extraneous packages I use with pygmt elsewhere). All the packages are versioned now, so you should be good to go with a simple:

`conda env create -f environment.yml`
`conda activate venturelli2020`

Matt
